version: '3.8'
services:
  app_database:
    container_name: app_database
    image: postgres
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/user_data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    networks:
      - appNet
  pg_admin:
    container_name: pgadmin4-server
    image: dpage/pgadmin4
    restart: always
    depends_on:
      app_database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - appNet
    volumes:
      - pgData:/var/lib/postgresql
#  cwms:
#    container_name: cwms
#    build: ./
#    ports:
#      - "8000:8000"
#    depends_on:
#      - app_database
#    networks:
#      - appNet
networks:
  appNet:
volumes:
  pgData: